### ISSUE TITLE
direct download links vs SBE packages

### ISSUE THREAD

**Issue by Karl-WE** [dell/azurestack-docs#112]
thankfully Dell has implemented direct download links in the matrix earlier.
now with Azure Stack HCI 23H2, I wonder how we can still use these, given the idea of "SBE packages".

An idea would be to provide the SBE packages DL directly on the matrix for each generation and version.

It seems like users accidently pulling wrong SBE for APEX for Azure (MC Nodes), rather AX 15/16 G nodes.
Seen one report on Azure Stack HCI slack but also noticed this at customers.

**Comment by mbjones0306** [comment]
Hey Karl,

There are direct links provided on the Release Notes page - https://www.dell.com/support/kbdoc/en-us/000224407/dell-for-microsoft-azure-stack-hci-ax-hardware-updates-release-notes. This page is also referenced in the output provided by the "Get-SolutionUpdate" command. Posting the direct link on the Release Notes page allows us to keep it within the bounds of the Dell Support website, as opposed to the public GitHub page. What we can do, to help minimize confusion, is to add a link to the Dell Support AX SBE Release Notes site within the Support Matrix page. Hopefully that will help!

**Comment by Karl-WE** [comment]
Thank you for your swift response and I like your idea how to reduce the confusion. 

What do you think about placing the link in the main page here?

https://dell.github.io/azurestack-docs/docs/hci/supportmatrix/

The supportability disclaimer on the sub pages is already complex.
