### ISSUE TITLE
Azure Stack HCI Support Matrix (2309)

### ISSUE THREAD

**Issue by syuheimurata** [dell/azurestack-docs#45]
I would like the download site link to be embedded in the Software Bundle listed on the Azure Stack HCI Support Matrix.

https://dell.github.io/azurestack-docs/docs/hci/supportmatrix/

![hci_link](https://github.com/dell/azurestack-docs/assets/39996543/029a8c3d-0180-44e6-8778-15498994be5d)

**Comment by wturner123** [comment]
Thanks for raising this! @syuheimurata @Nao-Maeshiro

This should be live now. You may need to hard-refresh (Ctrl + F5) if the changes are not showing for you.

Let us know if you have any issues.
