### ISSUE TITLE
Change Request | Support Matrix 

### ISSUE THREAD

**Issue by Nao-Maeshiro** [dell/azurestack-docs#46]
Please refer to the attached for details.
[Change Request.docx](https://github.com/dell/azurestack-docs/files/13330509/Change.Request.docx)

**Comment by cblackuk** [comment]
Duplicate of https://github.com/dell/azurestack-docs/issues/45

**Comment by cblackuk** [comment]
Will take into consideration when looking at https://github.com/dell/azurestack-docs/issues/45
