### ISSUE TITLE
All links under performance results are broken

### ISSUE THREAD

**Issue by born-slippy** [dell/azurestack-docs#95]
https://dell.github.io/azurestack-docs/docs/hci/storagestack/01-layers-below-s2d-stack/01-storagedevices/

[AX6515 - 2nodes, 16 cores and 4xSATA SSDs each](https://dell.github.io/azurestack-docs/azurestack-docs/docs/hci/storagestack/01-layers-below-s2d-stack/01-storagedevices/AX6515-All-Flash-8SATA-SSDs-32VMs-2Node.txt)
[AX6515 - 2nodes, 16 cores and 4xSATA SSDs each, secured core and deduplication enabled](https://dell.github.io/azurestack-docs/azurestack-docs/docs/hci/storagestack/01-layers-below-s2d-stack/01-storagedevices/AX6515-All-Flash-8SATA-SSDs-32VMs-2Node-SC-Dedup.txt)
[AX6515 - 2nodes, 16 cores and 4xSATA SSDs each, secured core enabled](https://dell.github.io/azurestack-docs/azurestack-docs/docs/hci/storagestack/01-layers-below-s2d-stack/01-storagedevices/AX6515-All-Flash-8SATA-SSDs-32VMs-2Node-SC.txt)
[AX6515 - 2nodes, 16 cores and 4xSATA SSDs each, secured core & BitLocker enabled](https://dell.github.io/azurestack-docs/azurestack-docs/docs/hci/storagestack/01-layers-below-s2d-stack/01-storagedevices/AX6515-All-Flash-8SATA-SSDs-32VMs-2Node-SC-BitLocker.txt)
[AX6515 - 2nodes, 16 cores and 8xSAS SSDs each](https://dell.github.io/azurestack-docs/azurestack-docs/docs/hci/storagestack/01-layers-below-s2d-stack/01-storagedevices/AX6515-All-Flash-16SAS-SSDs-32VMs-2nodes-azshci.txt)
[R640 - 2nodes, 32 cores and 8xNVMe SSDs each](https://dell.github.io/azurestack-docs/azurestack-docs/docs/hci/storagestack/01-layers-below-s2d-stack/01-storagedevices/R640-All-NVMe-16NVMe-64VMs-2Node.txt)

**Comment by wturner123** [comment]
@born-slippy - Many thanks for raising this to our attention. The links should now be fixed, you may need to Ctrl+F5 to refresh the cache.
